In [11]:
from DB import DB
import torch
from random import randint

In [2]:
dat = torch.load("./training_data/connect4/0.pt")

In [3]:
idx = 0

In [27]:
idx-=1

In [4]:
display(dat[0][idx], dat[1][idx], dat[2][idx])
idx +=1

tensor([[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]])

tensor([0.1475, 0.1440, 0.1414, 0.1414, 0.1414, 0.1396, 0.1449])

tensor(-1., dtype=torch.float64)

In [ ]:
idx

In [ ]:
dat[0][0] == dat[0][1]

In [5]:
model = torch.jit.load("../models/connect4/1.pt")

In [ ]:
# dat = torch.zeros(1, 2, 6, 7, device="cuda")

In [ ]:
(x := model(dat))

In [ ]:
torch.softmax(x[0], dim=1)

In [9]:
dat[0][6], dat[1][6], dat[2][6]

(tensor([[[0., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.]],
 
         [[1., 0., 0., 0., 0., 0., 1.],
          [0., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.]]]),
 tensor([0.0000, 0.1699, 0.1657, 0.1649, 0.1665, 0.1615, 0.1715]),
 tensor(-1., dtype=torch.float64))

In [6]:
X = dat[0][6].cuda().unsqueeze(0)
X
model.cuda()

RecursiveScriptModule(
  original_name=Connect4NN
  (inp): RecursiveScriptModule(
    original_name=Sequential
    (0): RecursiveScriptModule(original_name=ZeroPad2d)
    (1): RecursiveScriptModule(original_name=Conv2d)
  )
  (middle): RecursiveScriptModule(
    original_name=Middle
    (out): RecursiveScriptModule(
      original_name=Sequential
      (0): RecursiveScriptModule(
        original_name=ResNetBlock
        (out): RecursiveScriptModule(
          original_name=Residual
          (block): RecursiveScriptModule(
            original_name=ResBlock
            (out): RecursiveScriptModule(
              original_name=Sequential
              (0): RecursiveScriptModule(original_name=BatchNorm2d)
              (1): RecursiveScriptModule(original_name=ReLU)
              (2): RecursiveScriptModule(original_name=Conv2d)
              (3): RecursiveScriptModule(original_name=BatchNorm2d)
              (4): RecursiveScriptModule(original_name=ReLU)
              (5): RecursiveScrip

In [7]:
model(X)

(tensor([[-9.5874, -2.3886,  2.5633,  2.5704,  1.8340,  2.5548, -6.6105]],
        device='cuda:0', grad_fn=<AddmmBackward0>),
 tensor([-0.9053], device='cuda:0', grad_fn=<SqueezeBackward1>))

In [8]:
torch.softmax(model(X)[0], dim=1)

tensor([[1.5151e-06, 2.0269e-03, 2.8668e-01, 2.8873e-01, 1.3826e-01, 2.8427e-01,
         2.9737e-05]], device='cuda:0', grad_fn=<SoftmaxBackward0>)

In [15]:
i = randint(0, 10000)
X = dat[0][i].cuda().unsqueeze(0)
display(dat[0][i], dat[1][i], dat[2][i], model(X))

tensor([[[0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 0., 1., 0., 1.],
         [0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 1., 0., 1.],
         [0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 1., 0., 1.]],

        [[1., 1., 1., 0., 1., 0., 1.],
         [0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 0., 1., 0., 1.],
         [0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 0., 0., 1., 0., 1.],
         [0., 0., 0., 0., 0., 0., 0.]]])

tensor([0.0000, 0.0000, 0.3353, 0.3353, 0.0000, 0.3293, 0.0000])

tensor(-1., dtype=torch.float64)

(tensor([[-8.7699, -2.4058,  2.1819,  2.1793,  2.1636,  2.1612, -5.3667]],
        device='cuda:0', grad_fn=<DifferentiableGraphBackward>),
 tensor([0.6730], device='cuda:0', grad_fn=<DifferentiableGraphBackward>))